quant:
  wgts:
    dtype: uint8
    zero_point: PreScale
    enable_low_rank: false
    group_shapes:
      - - 1
        - 32
        - 1
        - 1
        - 1
    scale_dtypes:
      - null
  ipts:
    static: false
    dtype: uint8
    zero_point: PreScale
    group_shapes:
      - - 1
        - 32
        - 1
        - 1
        - 1
    scale_dtypes:
      - null
    allow_unsigned: true