quant:
  wgts:
    dtype: cint8
    enable_low_rank: false
    group_shapes:
      - - 1
        - 32
        - 1
        - 1
        - 1
    scale_dtypes:
      - null
    enable_kernel_lzs: false
  ipts:
    static: false
    dtype: cint8
    group_shapes:
      - - 1
        - 32
        - 1
        - 1
        - 1
    scale_dtypes:
      - null
    allow_unsigned: true
    enable_kernel_lzs: false
pipeline:
  shift_activations: true